export const  ACTION_CHANGE_FIRST_NAME = 'ACTION_CHANGE_FIRST_NAME',
              ACTION_CHANGE_LAST_NAME = 'ACTION_CHANGE_LAST_NAME',
              ACTION_CHANGE_EMAIL_NAME = 'ACTION_CHANGE_EMAIL_NAME',
              ACTION_CHANGE_CARD_TYPE = 'ACTION_CHANGE_CARD_TYPE',
              ACTION_CHANGE_DIFFICULT_TYPE = 'ACTION_CHANGE_DIFFICULT_TYPE',
              ACTION_CHANGE_TIME_GAME = 'ACTION_CHANGE_TIME_GAME',
              ACTION_ADD_STACK_ELEMENT = 'ACTION_ADD_STACK_ELEMENT',
              ACTION_DELETE_STACK_ELEMENT = 'ACTION_DELETE_STACK_ELEMENT',
              ACTION_DELETE_STACK_FIRST_ELEMENT='ACTION_DELETE_STACK_FIRST_ELEMENT',
              ACTION_CLEAR_STACK_ELEMENTS='ACTION_CLEAR_STACK_ELEMENTS',
              ACTION_CHANGE_ALL_GAME_RESULTS='ACTION_CHANGE_ALL_GAME_RESULTS';

